package com.litongjava.playwright.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTioBootAdminSystemUploadFile<M extends BaseTioBootAdminSystemUploadFile<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setMd5(java.lang.String md5) {
		set("md5", md5);
		return (M)this;
	}
	
	public java.lang.String getMd5() {
		return getStr("md5");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setSize(java.lang.Long size) {
		set("size", size);
		return (M)this;
	}
	
	public java.lang.Long getSize() {
		return getLong("size");
	}
	
	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}
	
	public M setPlatform(java.lang.String platform) {
		set("platform", platform);
		return (M)this;
	}
	
	public java.lang.String getPlatform() {
		return getStr("platform");
	}
	
	public M setRegionName(java.lang.String regionName) {
		set("region_name", regionName);
		return (M)this;
	}
	
	public java.lang.String getRegionName() {
		return getStr("region_name");
	}
	
	public M setBucketName(java.lang.String bucketName) {
		set("bucket_name", bucketName);
		return (M)this;
	}
	
	public java.lang.String getBucketName() {
		return getStr("bucket_name");
	}
	
	public M setFileId(java.lang.String fileId) {
		set("file_id", fileId);
		return (M)this;
	}
	
	public java.lang.String getFileId() {
		return getStr("file_id");
	}
	
	public M setTargetName(java.lang.String targetName) {
		set("target_name", targetName);
		return (M)this;
	}
	
	public java.lang.String getTargetName() {
		return getStr("target_name");
	}
	
	public M setTags(java.lang.Object tags) {
		set("tags", tags);
		return (M)this;
	}
	
	public java.lang.Object getTags() {
		return get("tags");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

