package com.litongjava.playwright.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaxKbProblemParagraphMapping<M extends BaseMaxKbProblemParagraphMapping<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setDatasetId(java.lang.Long datasetId) {
		set("dataset_id", datasetId);
		return (M)this;
	}
	
	public java.lang.Long getDatasetId() {
		return getLong("dataset_id");
	}
	
	public M setDocumentId(java.lang.Long documentId) {
		set("document_id", documentId);
		return (M)this;
	}
	
	public java.lang.Long getDocumentId() {
		return getLong("document_id");
	}
	
	public M setParagraphId(java.lang.Long paragraphId) {
		set("paragraph_id", paragraphId);
		return (M)this;
	}
	
	public java.lang.Long getParagraphId() {
		return getLong("paragraph_id");
	}
	
	public M setProblemId(java.lang.Long problemId) {
		set("problem_id", problemId);
		return (M)this;
	}
	
	public java.lang.Long getProblemId() {
		return getLong("problem_id");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

