package com.litongjava.playwright.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLlmVectorEmbedding<M extends BaseLlmVectorEmbedding<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setT(java.lang.String t) {
		set("t", t);
		return (M)this;
	}
	
	public java.lang.String getT() {
		return getStr("t");
	}
	
	public M setV(java.lang.String v) {
		set("v", v);
		return (M)this;
	}
	
	public java.lang.String getV() {
		return getStr("v");
	}
	
	public M setM(java.lang.String m) {
		set("m", m);
		return (M)this;
	}
	
	public java.lang.String getM() {
		return getStr("m");
	}
	
	public M setMd5(java.lang.String md5) {
		set("md5", md5);
		return (M)this;
	}
	
	public java.lang.String getMd5() {
		return getStr("md5");
	}
	
}

