package com.litongjava.playwright.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaxKbParagraphSummaryCache<M extends BaseMaxKbParagraphSummaryCache<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setMd5(java.lang.String md5) {
		set("md5", md5);
		return (M)this;
	}
	
	public java.lang.String getMd5() {
		return getStr("md5");
	}
	
	public M setSrc(java.lang.String src) {
		set("src", src);
		return (M)this;
	}
	
	public java.lang.String getSrc() {
		return getStr("src");
	}
	
	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public M setElapsed(java.lang.Long elapsed) {
		set("elapsed", elapsed);
		return (M)this;
	}
	
	public java.lang.Long getElapsed() {
		return getLong("elapsed");
	}
	
	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}
	
	public M setSystemFingerprint(java.lang.String systemFingerprint) {
		set("system_fingerprint", systemFingerprint);
		return (M)this;
	}
	
	public java.lang.String getSystemFingerprint() {
		return getStr("system_fingerprint");
	}
	
	public M setCompletionTokens(java.lang.Integer completionTokens) {
		set("completion_tokens", completionTokens);
		return (M)this;
	}
	
	public java.lang.Integer getCompletionTokens() {
		return getInt("completion_tokens");
	}
	
	public M setPromptTokens(java.lang.Integer promptTokens) {
		set("prompt_tokens", promptTokens);
		return (M)this;
	}
	
	public java.lang.Integer getPromptTokens() {
		return getInt("prompt_tokens");
	}
	
	public M setTotalTokens(java.lang.Integer totalTokens) {
		set("total_tokens", totalTokens);
		return (M)this;
	}
	
	public java.lang.Integer getTotalTokens() {
		return getInt("total_tokens");
	}
	
}

