package com.litongjava.playwright.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaxKbApplicationTempSetting<M extends BaseMaxKbApplicationTempSetting<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setSetting(java.lang.String setting) {
		set("setting", setting);
		return (M)this;
	}
	
	public java.lang.String getSetting() {
		return getStr("setting");
	}
	
}

