package com.litongjava.playwright.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaxKbDocument<M extends BaseMaxKbDocument<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setFileId(java.lang.Long fileId) {
		set("file_id", fileId);
		return (M)this;
	}
	
	public java.lang.Long getFileId() {
		return getLong("file_id");
	}
	
	public M setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setCharLength(java.lang.Integer charLength) {
		set("char_length", charLength);
		return (M)this;
	}
	
	public java.lang.Integer getCharLength() {
		return getInt("char_length");
	}
	
	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public M setIsActive(java.lang.Boolean isActive) {
		set("is_active", isActive);
		return (M)this;
	}
	
	public java.lang.Boolean getIsActive() {
		return getBoolean("is_active");
	}
	
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public M setMeta(java.lang.String meta) {
		set("meta", meta);
		return (M)this;
	}
	
	public java.lang.String getMeta() {
		return getStr("meta");
	}
	
	public M setDatasetId(java.lang.Long datasetId) {
		set("dataset_id", datasetId);
		return (M)this;
	}
	
	public java.lang.Long getDatasetId() {
		return getLong("dataset_id");
	}
	
	public M setHitHandlingMethod(java.lang.String hitHandlingMethod) {
		set("hit_handling_method", hitHandlingMethod);
		return (M)this;
	}
	
	public java.lang.String getHitHandlingMethod() {
		return getStr("hit_handling_method");
	}
	
	public M setDirectlyReturnSimilarity(java.lang.Double directlyReturnSimilarity) {
		set("directly_return_similarity", directlyReturnSimilarity);
		return (M)this;
	}
	
	public java.lang.Double getDirectlyReturnSimilarity() {
		return getDouble("directly_return_similarity");
	}
	
	public M setParagraphCount(java.lang.Integer paragraphCount) {
		set("paragraph_count", paragraphCount);
		return (M)this;
	}
	
	public java.lang.Integer getParagraphCount() {
		return getInt("paragraph_count");
	}
	
	public M setFiles(java.lang.Object files) {
		set("files", files);
		return (M)this;
	}
	
	public java.lang.Object getFiles() {
		return get("files");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

