package com.litongjava.playwright.model.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTioBootAdminSystemUsers<M extends BaseTioBootAdminSystemUsers<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}
	
	public java.lang.String getNickname() {
		return getStr("nickname");
	}
	
	public M setSignature(java.lang.String signature) {
		set("signature", signature);
		return (M)this;
	}
	
	public java.lang.String getSignature() {
		return getStr("signature");
	}
	
	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	public M setGroupName(java.lang.String groupName) {
		set("group_name", groupName);
		return (M)this;
	}
	
	public java.lang.String getGroupName() {
		return getStr("group_name");
	}
	
	public M setTags(java.lang.Object tags) {
		set("tags", tags);
		return (M)this;
	}
	
	public java.lang.Object getTags() {
		return get("tags");
	}
	
	public M setNotifyCount(java.lang.Integer notifyCount) {
		set("notify_count", notifyCount);
		return (M)this;
	}
	
	public java.lang.Integer getNotifyCount() {
		return getInt("notify_count");
	}
	
	public M setUnreadCount(java.lang.Integer unreadCount) {
		set("unread_count", unreadCount);
		return (M)this;
	}
	
	public java.lang.Integer getUnreadCount() {
		return getInt("unread_count");
	}
	
	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}
	
	public java.lang.String getCountry() {
		return getStr("country");
	}
	
	public M setAccess(java.lang.String access) {
		set("access", access);
		return (M)this;
	}
	
	public java.lang.String getAccess() {
		return getStr("access");
	}
	
	public M setGeographic(java.lang.Object geographic) {
		set("geographic", geographic);
		return (M)this;
	}
	
	public java.lang.Object getGeographic() {
		return get("geographic");
	}
	
	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public M setDeptId(java.lang.Long deptId) {
		set("dept_id", deptId);
		return (M)this;
	}
	
	public java.lang.Long getDeptId() {
		return getLong("dept_id");
	}
	
	public M setPostIds(java.lang.String postIds) {
		set("post_ids", postIds);
		return (M)this;
	}
	
	public java.lang.String getPostIds() {
		return getStr("post_ids");
	}
	
	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}
	
	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public M setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
		return (M)this;
	}
	
	public java.lang.String getLoginIp() {
		return getStr("login_ip");
	}
	
	public M setLoginDate(java.util.Date loginDate) {
		set("login_date", loginDate);
		return (M)this;
	}
	
	public java.util.Date getLoginDate() {
		return getDate("login_date");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

