package com.litongjava.playwright.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaxKbApplicationDatasetMapping<M extends BaseMaxKbApplicationDatasetMapping<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setApplicationId(java.lang.Long applicationId) {
		set("application_id", applicationId);
		return (M)this;
	}
	
	public java.lang.Long getApplicationId() {
		return getLong("application_id");
	}
	
	public M setDatasetId(java.lang.Long datasetId) {
		set("dataset_id", datasetId);
		return (M)this;
	}
	
	public java.lang.Long getDatasetId() {
		return getLong("dataset_id");
	}
	
}

