package com.litongjava.playwright.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePerplexicaChatMessage<M extends BasePerplexicaChatMessage<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setChatId(java.lang.Long chatId) {
		set("chat_id", chatId);
		return (M)this;
	}
	
	public java.lang.Long getChatId() {
		return getLong("chat_id");
	}
	
	public M setRole(java.lang.String role) {
		set("role", role);
		return (M)this;
	}
	
	public java.lang.String getRole() {
		return getStr("role");
	}
	
	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public M setRewrited(java.lang.String rewrited) {
		set("rewrited", rewrited);
		return (M)this;
	}
	
	public java.lang.String getRewrited() {
		return getStr("rewrited");
	}
	
	public M setSources(java.lang.String sources) {
		set("sources", sources);
		return (M)this;
	}
	
	public java.lang.String getSources() {
		return getStr("sources");
	}
	
	public M setMetadata(java.lang.String metadata) {
		set("metadata", metadata);
		return (M)this;
	}
	
	public java.lang.String getMetadata() {
		return getStr("metadata");
	}
	
	public M setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
		return (M)this;
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

