package com.litongjava.playwright.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaxKbDocumentTranslate<M extends BaseMaxKbDocumentTranslate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setSrcLang(java.lang.String srcLang) {
		set("src_lang", srcLang);
		return (M)this;
	}
	
	public java.lang.String getSrcLang() {
		return getStr("src_lang");
	}
	
	public M setDstLang(java.lang.String dstLang) {
		set("dst_lang", dstLang);
		return (M)this;
	}
	
	public java.lang.String getDstLang() {
		return getStr("dst_lang");
	}
	
	public M setSrcContent(java.lang.String srcContent) {
		set("src_content", srcContent);
		return (M)this;
	}
	
	public java.lang.String getSrcContent() {
		return getStr("src_content");
	}
	
	public M setDstContent(java.lang.String dstContent) {
		set("dst_content", dstContent);
		return (M)this;
	}
	
	public java.lang.String getDstContent() {
		return getStr("dst_content");
	}
	
	public M setFiles(java.lang.String files) {
		set("files", files);
		return (M)this;
	}
	
	public java.lang.String getFiles() {
		return getStr("files");
	}
	
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

