package com.litongjava.playwright.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaxKbApplicationAccessToken<M extends BaseMaxKbApplicationAccessToken<M>> extends Model<M> implements IBean {

	public M setApplicationId(java.lang.Long applicationId) {
		set("application_id", applicationId);
		return (M)this;
	}
	
	public java.lang.Long getApplicationId() {
		return getLong("application_id");
	}
	
	public M setAccessToken(java.lang.Long accessToken) {
		set("access_token", accessToken);
		return (M)this;
	}
	
	public java.lang.Long getAccessToken() {
		return getLong("access_token");
	}
	
	public M setIsActive(java.lang.Boolean isActive) {
		set("is_active", isActive);
		return (M)this;
	}
	
	public java.lang.Boolean getIsActive() {
		return getBoolean("is_active");
	}
	
	public M setAccessNum(java.lang.Integer accessNum) {
		set("access_num", accessNum);
		return (M)this;
	}
	
	public java.lang.Integer getAccessNum() {
		return getInt("access_num");
	}
	
	public M setWhiteActive(java.lang.Boolean whiteActive) {
		set("white_active", whiteActive);
		return (M)this;
	}
	
	public java.lang.Boolean getWhiteActive() {
		return getBoolean("white_active");
	}
	
	public M setWhiteList(java.lang.String[] whiteList) {
		set("white_list", whiteList);
		return (M)this;
	}
	
	public java.lang.String[] getWhiteList() {
		return get("white_list");
	}
	
	public M setShowSource(java.lang.Boolean showSource) {
		set("show_source", showSource);
		return (M)this;
	}
	
	public java.lang.Boolean getShowSource() {
		return getBoolean("show_source");
	}
	
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

