package com.litongjava.playwright.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaxKbModel<M extends BaseMaxKbModel<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public M setModelType(java.lang.String modelType) {
		set("model_type", modelType);
		return (M)this;
	}
	
	public java.lang.String getModelType() {
		return getStr("model_type");
	}
	
	public M setModelName(java.lang.String modelName) {
		set("model_name", modelName);
		return (M)this;
	}
	
	public java.lang.String getModelName() {
		return getStr("model_name");
	}
	
	public M setProvider(java.lang.String provider) {
		set("provider", provider);
		return (M)this;
	}
	
	public java.lang.String getProvider() {
		return getStr("provider");
	}
	
	public M setCredential(java.lang.String credential) {
		set("credential", credential);
		return (M)this;
	}
	
	public java.lang.String getCredential() {
		return getStr("credential");
	}
	
	public M setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}
	
	public M setMeta(java.lang.String meta) {
		set("meta", meta);
		return (M)this;
	}
	
	public java.lang.String getMeta() {
		return getStr("meta");
	}
	
	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public M setPermissionType(java.lang.String permissionType) {
		set("permission_type", permissionType);
		return (M)this;
	}
	
	public java.lang.String getPermissionType() {
		return getStr("permission_type");
	}
	
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

