package com.litongjava.playwright.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaxKbApplicationChatRecord<M extends BaseMaxKbApplicationChatRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setVoteStatus(java.lang.String voteStatus) {
		set("vote_status", voteStatus);
		return (M)this;
	}
	
	public java.lang.String getVoteStatus() {
		return getStr("vote_status");
	}
	
	public M setProblemText(java.lang.String problemText) {
		set("problem_text", problemText);
		return (M)this;
	}
	
	public java.lang.String getProblemText() {
		return getStr("problem_text");
	}
	
	public M setAnswerText(java.lang.String answerText) {
		set("answer_text", answerText);
		return (M)this;
	}
	
	public java.lang.String getAnswerText() {
		return getStr("answer_text");
	}
	
	public M setMessageTokens(java.lang.Integer messageTokens) {
		set("message_tokens", messageTokens);
		return (M)this;
	}
	
	public java.lang.Integer getMessageTokens() {
		return getInt("message_tokens");
	}
	
	public M setAnswerTokens(java.lang.Integer answerTokens) {
		set("answer_tokens", answerTokens);
		return (M)this;
	}
	
	public java.lang.Integer getAnswerTokens() {
		return getInt("answer_tokens");
	}
	
	public M setConst(java.lang.Integer _const) {
		set("const", _const);
		return (M)this;
	}
	
	public java.lang.Integer getConst() {
		return getInt("const");
	}
	
	public M setDetails(java.lang.String details) {
		set("details", details);
		return (M)this;
	}
	
	public java.lang.String getDetails() {
		return getStr("details");
	}
	
	public M setImproveParagraphIdList(java.lang.Long[] improveParagraphIdList) {
		set("improve_paragraph_id_list", improveParagraphIdList);
		return (M)this;
	}
	
	public java.lang.Long[] getImproveParagraphIdList() {
		return get("improve_paragraph_id_list");
	}
	
	public M setRunTime(java.lang.Double runTime) {
		set("run_time", runTime);
		return (M)this;
	}
	
	public java.lang.Double getRunTime() {
		return getDouble("run_time");
	}
	
	public M setIndex(java.lang.Integer index) {
		set("index", index);
		return (M)this;
	}
	
	public java.lang.Integer getIndex() {
		return getInt("index");
	}
	
	public M setChatId(java.lang.Long chatId) {
		set("chat_id", chatId);
		return (M)this;
	}
	
	public java.lang.Long getChatId() {
		return getLong("chat_id");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

