package com.litongjava.playwright.model;

import com.litongjava.db.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("llm_chat_history", "id", LlmChatHistory.class);
		arp.addMapping("llm_chat_session", "id", LlmChatSession.class);
		arp.addMapping("llm_intent_classification", "id", LlmIntentClassification.class);
		arp.addMapping("llm_intent_question", "id", LlmIntentQuestion.class);
		arp.addMapping("llm_question_recommend", "id", LlmQuestionRecommend.class);
		arp.addMapping("llm_vector_embedding", "id", LlmVectorEmbedding.class);
		arp.addMapping("max_kb_application", "id", MaxKbApplication.class);
		arp.addMapping("max_kb_application_access_token", "application_id", MaxKbApplicationAccessToken.class);
		arp.addMapping("max_kb_application_chat", "id", MaxKbApplicationChat.class);
		arp.addMapping("max_kb_application_chat_record", "id", MaxKbApplicationChatRecord.class);
		arp.addMapping("max_kb_application_dataset_mapping", "id", MaxKbApplicationDatasetMapping.class);
		arp.addMapping("max_kb_application_public_access_client", "id", MaxKbApplicationPublicAccessClient.class);
		arp.addMapping("max_kb_application_temp_setting", "id", MaxKbApplicationTempSetting.class);
		arp.addMapping("max_kb_dataset", "id", MaxKbDataset.class);
		arp.addMapping("max_kb_document", "id", MaxKbDocument.class);
		arp.addMapping("max_kb_document_markdown_cache", "id", MaxKbDocumentMarkdownCache.class);
		arp.addMapping("max_kb_document_markdown_page_cache", "id", MaxKbDocumentMarkdownPageCache.class);
		arp.addMapping("max_kb_document_translate", "id", MaxKbDocumentTranslate.class);
		arp.addMapping("max_kb_document_translate_cache", "id", MaxKbDocumentTranslateCache.class);
		arp.addMapping("max_kb_embedding_cache", "id", MaxKbEmbeddingCache.class);
		arp.addMapping("max_kb_file", "id", MaxKbFile.class);
		arp.addMapping("max_kb_model", "id", MaxKbModel.class);
		arp.addMapping("max_kb_paragraph", "id", MaxKbParagraph.class);
		arp.addMapping("max_kb_paragraph_summary_cache", "id", MaxKbParagraphSummaryCache.class);
		arp.addMapping("max_kb_problem", "id", MaxKbProblem.class);
		arp.addMapping("max_kb_problem_paragraph_mapping", "id", MaxKbProblemParagraphMapping.class);
		arp.addMapping("max_kb_sentence", "id", MaxKbSentence.class);
		arp.addMapping("max_kb_task", "id", MaxKbTask.class);
		arp.addMapping("max_kb_user", "id", MaxKbUser.class);
		arp.addMapping("max_kb_user_token", "id", MaxKbUserToken.class);
		arp.addMapping("max_kb_web_page_cache", "id", MaxKbWebPageCache.class);
		arp.addMapping("max_kb_web_page_description", "id", MaxKbWebPageDescription.class);
		arp.addMapping("palywright_brower_web_page_cache", "id", PalywrightBrowerWebPageCache.class);
		arp.addMapping("perplexica_chat_message", "id", PerplexicaChatMessage.class);
		arp.addMapping("perplexica_chat_session", "id", PerplexicaChatSession.class);
		arp.addMapping("tio_boot_admin_sa_token", "id", TioBootAdminSaToken.class);
		arp.addMapping("tio_boot_admin_system_constants_config", "id", TioBootAdminSystemConstantsConfig.class);
		arp.addMapping("tio_boot_admin_system_upload_file", "id", TioBootAdminSystemUploadFile.class);
		arp.addMapping("tio_boot_admin_system_users", "id", TioBootAdminSystemUsers.class);
		arp.addMapping("user_asked_questions", "id", UserAskedQuestions.class);
	}
}


