package com.litongjava.playwright.model;

import com.litongjava.db.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("hawaii_kapioalni_web_page", "id", HawaiiKapioalniWebPage.class);
		arp.addMapping("hawaii_web_page", "id", HawaiiWebPage.class);
		arp.addMapping("web_page_cache", "id", WebPageCache.class);
		arp.addMapping("web_page_url", "id", WebPageUrl.class);
	}
}


