package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseLlmIntentClassification;

/**
 * Generated by java-db.
 */
public class LlmIntentClassification extends BaseLlmIntentClassification<LlmIntentClassification> {
  private static final long serialVersionUID = 1L;
	public static final LlmIntentClassification dao = new LlmIntentClassification().dao();
	/**
	 * 
	 */
  public static final String tableName = "llm_intent_classification";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String name = "name";
  //java.lang.String 
  public static final String description = "description";
  //java.lang.String 
  public static final String action = "action";
  //java.lang.String 
  public static final String prompt = "prompt";
  //java.lang.String 
  public static final String additionalInfo = "additional_info";
  //java.lang.Integer 
  public static final String includeGeneral = "include_general";
  //java.lang.String 
  public static final String remark = "remark";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";
  //java.lang.String 
  public static final String env = "env";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

