package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseLlmIntentQuestion;

/**
 * Generated by java-db.
 */
public class LlmIntentQuestion extends BaseLlmIntentQuestion<LlmIntentQuestion> {
  private static final long serialVersionUID = 1L;
	public static final LlmIntentQuestion dao = new LlmIntentQuestion().dao();
	/**
	 * 
	 */
  public static final String tableName = "llm_intent_question";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String question = "question";
  //java.lang.Long 
  public static final String categoryId = "category_id";
  //java.lang.String 
  public static final String remark = "remark";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";
  //java.lang.String 
  public static final String questionVector = "question_vector";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

