package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseLlmQuestionRecommend;

/**
 * Generated by java-db.
 */
public class LlmQuestionRecommend extends BaseLlmQuestionRecommend<LlmQuestionRecommend> {
  private static final long serialVersionUID = 1L;
	public static final LlmQuestionRecommend dao = new LlmQuestionRecommend().dao();
	/**
	 * 
	 */
  public static final String tableName = "llm_question_recommend";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.Integer 
  public static final String orders = "orders";
  //java.lang.String 
  public static final String avatar = "avatar";
  //java.lang.String 
  public static final String title = "title";
  //java.lang.String 
  public static final String content = "content";
  //java.lang.String 
  public static final String env = "env";
  //java.lang.String 
  public static final String remark = "remark";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

