package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseLlmVectorEmbedding;

/**
 * Generated by java-db.
 */
public class LlmVectorEmbedding extends BaseLlmVectorEmbedding<LlmVectorEmbedding> {
  private static final long serialVersionUID = 1L;
	public static final LlmVectorEmbedding dao = new LlmVectorEmbedding().dao();
	/**
	 * 
	 */
  public static final String tableName = "llm_vector_embedding";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String t = "t";
  //java.lang.String 
  public static final String v = "v";
  //java.lang.String 
  public static final String m = "m";
  //java.lang.String 
  public static final String md5 = "md5";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

