package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseMaxKbWebPageCache;

/**
 * Generated by java-db.
 */
public class MaxKbWebPageCache extends BaseMaxKbWebPageCache<MaxKbWebPageCache> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbWebPageCache dao = new MaxKbWebPageCache().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_web_page_cache";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String url = "url";
  //java.lang.String 
  public static final String content = "content";
  //java.lang.String 
  public static final String remark = "remark";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

