package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseMaxKbDocument;

/**
 * Generated by java-db.
 */
public class MaxKbDocument extends BaseMaxKbDocument<MaxKbDocument> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbDocument dao = new MaxKbDocument().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_document";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.Long 
  public static final String fileId = "file_id";
  //java.lang.Long 
  public static final String userId = "user_id";
  //java.lang.String 
  public static final String title = "title";
  //java.lang.String 
  public static final String name = "name";
  //java.lang.Integer 
  public static final String charLength = "char_length";
  //java.lang.String 
  public static final String status = "status";
  //java.lang.Boolean 
  public static final String isActive = "is_active";
  //java.lang.String 
  public static final String type = "type";
  //java.lang.String 
  public static final String meta = "meta";
  //java.lang.Long 
  public static final String datasetId = "dataset_id";
  //java.lang.String 
  public static final String hitHandlingMethod = "hit_handling_method";
  //java.lang.Double 
  public static final String directlyReturnSimilarity = "directly_return_similarity";
  //java.lang.Integer 
  public static final String paragraphCount = "paragraph_count";
  //java.lang.Object 
  public static final String files = "files";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

