package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseMaxKbApplicationTempSetting;

/**
 * Generated by java-db.
 */
public class MaxKbApplicationTempSetting extends BaseMaxKbApplicationTempSetting<MaxKbApplicationTempSetting> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbApplicationTempSetting dao = new MaxKbApplicationTempSetting().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_application_temp_setting";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String setting = "setting";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

