package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseMaxKbDocumentMarkdownPageCache;

/**
 * Generated by java-db.
 */
public class MaxKbDocumentMarkdownPageCache extends BaseMaxKbDocumentMarkdownPageCache<MaxKbDocumentMarkdownPageCache> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbDocumentMarkdownPageCache dao = new MaxKbDocumentMarkdownPageCache().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_document_markdown_page_cache";
  public static final String primaryKey = "id";
  //java.lang.String 
  public static final String id = "id";
  //java.lang.String 
  public static final String target = "target";
  //java.lang.String 
  public static final String content = "content";
  //java.lang.Long 
  public static final String elapsed = "elapsed";
  //java.lang.String 
  public static final String model = "model";
  //java.lang.String 
  public static final String systemFingerprint = "system_fingerprint";
  //java.lang.Integer 
  public static final String completionTokens = "completion_tokens";
  //java.lang.Integer 
  public static final String promptTokens = "prompt_tokens";
  //java.lang.Integer 
  public static final String totalTokens = "total_tokens";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

