package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseMaxKbModel;

/**
 * Generated by java-db.
 */
public class MaxKbModel extends BaseMaxKbModel<MaxKbModel> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbModel dao = new MaxKbModel().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_model";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String name = "name";
  //java.lang.String 
  public static final String modelType = "model_type";
  //java.lang.String 
  public static final String modelName = "model_name";
  //java.lang.String 
  public static final String provider = "provider";
  //java.lang.String 
  public static final String credential = "credential";
  //java.lang.Long 
  public static final String userId = "user_id";
  //java.lang.String 
  public static final String meta = "meta";
  //java.lang.String 
  public static final String status = "status";
  //java.lang.String 
  public static final String permissionType = "permission_type";
  //java.lang.String 
  public static final String remark = "remark";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

