package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseMaxKbProblem;

/**
 * Generated by java-db.
 */
public class MaxKbProblem extends BaseMaxKbProblem<MaxKbProblem> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbProblem dao = new MaxKbProblem().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_problem";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String content = "content";
  //java.lang.Integer 
  public static final String hitNum = "hit_num";
  //java.lang.Long 
  public static final String datasetId = "dataset_id";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

