package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseMaxKbWebPageDescription;

/**
 * Generated by java-db.
 */
public class MaxKbWebPageDescription extends BaseMaxKbWebPageDescription<MaxKbWebPageDescription> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbWebPageDescription dao = new MaxKbWebPageDescription().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_web_page_description";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String description = "description";
  //java.lang.String 
  public static final String content = "content";
  //java.lang.String 
  public static final String descriptionMd5 = "description_md5";
  //java.lang.String 
  public static final String contentMd5 = "content_md5";
  //java.lang.String 
  public static final String descriptiontVector = "descriptiont_vector";
  //java.lang.Long 
  public static final String descriptionVectorId = "description_vector_id";
  //java.lang.String 
  public static final String contentVector = "content_vector";
  //java.lang.Long 
  public static final String contentVectorId = "content_vector_id";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

