package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseMaxKbApplicationDatasetMapping;

/**
 * Generated by java-db.
 */
public class MaxKbApplicationDatasetMapping extends BaseMaxKbApplicationDatasetMapping<MaxKbApplicationDatasetMapping> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbApplicationDatasetMapping dao = new MaxKbApplicationDatasetMapping().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_application_dataset_mapping";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.Long 
  public static final String applicationId = "application_id";
  //java.lang.Long 
  public static final String datasetId = "dataset_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

