package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseMaxKbDocumentTranslate;

/**
 * Generated by java-db.
 */
public class MaxKbDocumentTranslate extends BaseMaxKbDocumentTranslate<MaxKbDocumentTranslate> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbDocumentTranslate dao = new MaxKbDocumentTranslate().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_document_translate";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String name = "name";
  //java.lang.String 
  public static final String srcLang = "src_lang";
  //java.lang.String 
  public static final String dstLang = "dst_lang";
  //java.lang.String 
  public static final String srcContent = "src_content";
  //java.lang.String 
  public static final String dstContent = "dst_content";
  //java.lang.String 
  public static final String files = "files";
  //java.lang.String 
  public static final String remark = "remark";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

