package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseMaxKbTask;

/**
 * Generated by java-db.
 */
public class MaxKbTask extends BaseMaxKbTask<MaxKbTask> {
  private static final long serialVersionUID = 1L;
	public static final MaxKbTask dao = new MaxKbTask().dao();
	/**
	 * 
	 */
  public static final String tableName = "max_kb_task";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.Long 
  public static final String fileId = "file_id";
  //java.lang.String 
  public static final String fileName = "file_name";
  //java.lang.Long 
  public static final String fileSize = "file_size";
  //java.lang.Long 
  public static final String datasetId = "dataset_id";
  //java.lang.Long 
  public static final String documentId = "document_id";
  //java.lang.Integer 
  public static final String progress = "progress";
  //java.lang.String 
  public static final String status = "status";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

