package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BasePalywrightBrowerWebPageCache;

/**
 * Generated by java-db.
 */
public class PalywrightBrowerWebPageCache extends BasePalywrightBrowerWebPageCache<PalywrightBrowerWebPageCache> {
  private static final long serialVersionUID = 1L;
	public static final PalywrightBrowerWebPageCache dao = new PalywrightBrowerWebPageCache().dao();
	/**
	 * 
	 */
  public static final String tableName = "palywright_brower_web_page_cache";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String url = "url";
  //java.lang.String 
  public static final String text = "text";
  //java.lang.String 
  public static final String html = "html";
  //java.lang.String 
  public static final String markdown = "markdown";
  //java.lang.String 
  public static final String remark = "remark";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

