package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseTioBootAdminSystemConstantsConfig;

/**
 * Generated by java-db.
 */
public class TioBootAdminSystemConstantsConfig extends BaseTioBootAdminSystemConstantsConfig<TioBootAdminSystemConstantsConfig> {
  private static final long serialVersionUID = 1L;
	public static final TioBootAdminSystemConstantsConfig dao = new TioBootAdminSystemConstantsConfig().dao();
	/**
	 * 
	 */
  public static final String tableName = "tio_boot_admin_system_constants_config";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String keyName = "key_name";
  //java.lang.String 
  public static final String keyValue = "key_value";
  //java.lang.String 
  public static final String remark = "remark";
  //java.util.Date 
  public static final String loginDate = "login_date";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

