package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseTioBootAdminSystemUsers;

/**
 * Generated by java-db.
 */
public class TioBootAdminSystemUsers extends BaseTioBootAdminSystemUsers<TioBootAdminSystemUsers> {
  private static final long serialVersionUID = 1L;
	public static final TioBootAdminSystemUsers dao = new TioBootAdminSystemUsers().dao();
	/**
	 * 
	 */
  public static final String tableName = "tio_boot_admin_system_users";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String username = "username";
  //java.lang.String 
  public static final String password = "password";
  //java.lang.String 
  public static final String nickname = "nickname";
  //java.lang.String 
  public static final String signature = "signature";
  //java.lang.String 
  public static final String title = "title";
  //java.lang.String 
  public static final String groupName = "group_name";
  //java.lang.Object 
  public static final String tags = "tags";
  //java.lang.Integer 
  public static final String notifyCount = "notify_count";
  //java.lang.Integer 
  public static final String unreadCount = "unread_count";
  //java.lang.String 
  public static final String country = "country";
  //java.lang.String 
  public static final String access = "access";
  //java.lang.Object 
  public static final String geographic = "geographic";
  //java.lang.String 
  public static final String address = "address";
  //java.lang.String 
  public static final String remark = "remark";
  //java.lang.Long 
  public static final String deptId = "dept_id";
  //java.lang.String 
  public static final String postIds = "post_ids";
  //java.lang.String 
  public static final String email = "email";
  //java.lang.String 
  public static final String phone = "phone";
  //java.lang.Integer 
  public static final String sex = "sex";
  //java.lang.String 
  public static final String avatar = "avatar";
  //java.lang.Integer 
  public static final String status = "status";
  //java.lang.String 
  public static final String loginIp = "login_ip";
  //java.util.Date 
  public static final String loginDate = "login_date";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

