package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseTioBootAdminSystemUploadFile;

/**
 * Generated by java-db.
 */
public class TioBootAdminSystemUploadFile extends BaseTioBootAdminSystemUploadFile<TioBootAdminSystemUploadFile> {
  private static final long serialVersionUID = 1L;
	public static final TioBootAdminSystemUploadFile dao = new TioBootAdminSystemUploadFile().dao();
	/**
	 * 
	 */
  public static final String tableName = "tio_boot_admin_system_upload_file";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String md5 = "md5";
  //java.lang.String 
  public static final String name = "name";
  //java.lang.Long 
  public static final String size = "size";
  //java.lang.String 
  public static final String userId = "user_id";
  //java.lang.String 
  public static final String platform = "platform";
  //java.lang.String 
  public static final String regionName = "region_name";
  //java.lang.String 
  public static final String bucketName = "bucket_name";
  //java.lang.String 
  public static final String fileId = "file_id";
  //java.lang.String 
  public static final String targetName = "target_name";
  //java.lang.Object 
  public static final String tags = "tags";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

