package com.litongjava.playwright.model;

import com.litongjava.playwright.model.base.BaseWebPageUrl;

/**
 * Generated by java-db.
 */
public class WebPageUrl extends BaseWebPageUrl<WebPageUrl> {
  private static final long serialVersionUID = 1L;
	public static final WebPageUrl dao = new WebPageUrl().dao();
	/**
	 * 
	 */
  public static final String tableName = "web_page_url";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String url = "url";
  //java.lang.Integer 
  public static final String status = "status";
  //java.lang.Integer 
  public static final String tried = "tried";
  //java.lang.String 
  public static final String remark = "remark";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

